swagger: "2.0"
info:
  title: bank/v1/bank.proto
  version: version not set
tags:
  - name: BankService
    description: BankService description -- which should not be used in place of the documentation comment!
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/bank/current_balance/{account_number}:
    get:
      summary: BankService summary -- which should not be used in place of the documentation comment!
      description: BankService description -- which should not be used in place of the documentation comment!
      operationId: BankService_GetCurrentBalance
      responses:
        "200":
          description: Return current account balance
          schema:
            $ref: '#/definitions/v1CurrentBalanceResponse'
        "400":
          description: Returned when given account number is not exists
          schema: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: account_number
          in: path
          required: true
          type: string
      tags:
        - BankService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  typeDate:
    type: object
    properties:
      year:
        type: integer
        format: int32
        description: |-
          Year of the date. Must be from 1 to 9999, or 0 to specify a date without
          a year.
      month:
        type: integer
        format: int32
        description: |-
          Month of a year. Must be from 1 to 12, or 0 to specify a year without a
          month and day.
      day:
        type: integer
        format: int32
        description: |-
          Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
          to specify a year by itself or a year and month where the day isn't
          significant.
    description: |-
      * A full date, with non-zero year, month, and day values
      * A month and day value, with a zero year, such as an anniversary
      * A year on its own, with zero month and day values
      * A year and month value, with a zero day, such as a credit card expiration
      date

      Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and
      `google.protobuf.Timestamp`.
    title: |-
      Represents a whole or partial calendar date, such as a birthday. The time of
      day and time zone are either specified elsewhere or are insignificant. The
      date is relative to the Gregorian Calendar. This can represent one of the
      following:
  v1CurrentBalanceResponse:
    type: object
    properties:
      amount:
        type: number
        format: double
      current_date:
        $ref: '#/definitions/typeDate'
